const seedBrands = [
  { id: 1, name: "Apple", logo_url: "/logos/apple.svg" },
  { id: 2, name: "Samsung", logo_url: "/logos/samsung.svg" },
  { id: 3, name: "OnePlus", logo_url: "/logos/oneplus.svg" },
  { id: 4, name: "Google", logo_url: "/logos/google.svg" },
  { id: 5, name: "Nothing", logo_url: "/logos/nothing.svg" },
  { id: 6, name: "Xiaomi", logo_url: "/logos/xiaomi.svg" },
  { id: 7, name: "Oppo", logo_url: "/logos/oppo.svg" },
  { id: 8, name: "Vivo", logo_url: "/logos/vivo.svg" },
  { id: 9, name: "Motorola", logo_url: "/logos/motorola.svg" }
];

const seedPhones = [
  {
    brand_id: 2,
    model: "Galaxy S25 Ultra",
    launch_date: "2025-01-31",
    price_inr: 134999,
    display_size: 6.8,
    display_type: "Dynamic AMOLED 2X LTPO",
    refresh_rate: 120,
    resolution: "3120 x 1440 (QHD+)",
    processor: "Snapdragon 8 Elite",
    gpu: "Adreno 830",
    ram_gb: 12,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "200MP Main (OIS) + 50MP Periscope (5x) + 50MP Telephoto (3x) + 50MP Ultra-wide",
    front_camera_spec: "12MP",
    battery_capacity: 5000,
    charging_speed: 45,
    wireless_charging: true,
    android_version: "Android 15 (One UI 7.1)",
    software_updates_years: 7,
    weight_g: 219,
    build_quality: "Titanium Frame, Gorilla Armor Front",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 7, NFC, UWB",
    overall_score: 97,
    performance_score: 99,
    camera_score: 98,
    battery_score: 90,
    gaming_score: 98,
    display_score: 99,
    value_for_money_score: 75,
    pros: JSON.stringify([
      "Superb performance with Snapdragon 8 Elite",
      "Class-leading camera system with 50MP optical sensors",
      "Stunning anti-reflective screen with premium titanium build",
      "Industry best 7 years updates support"
    ]),
    cons: JSON.stringify([
      "Very premium, expensive pricing",
      "No charger in the retail packaging",
      "Slow 45W charging speed compared to alternatives"
    ]),
    image_url: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 1,
    model: "iPhone 16 Pro Max",
    launch_date: "2024-09-20",
    price_inr: 144900,
    display_size: 6.9,
    display_type: "Super Retina XDR LTPO OLED",
    refresh_rate: 120,
    resolution: "2868 x 1320",
    processor: "Apple A18 Pro (3nm)",
    gpu: "Apple GPU (6-core)",
    ram_gb: 8,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "48MP Main (Sensor-shift OIS) + 48MP Ultra-wide + 12MP Telephoto (5x Optical)",
    front_camera_spec: "12MP (OIS)",
    battery_capacity: 4685,
    charging_speed: 30,
    wireless_charging: true,
    android_version: "iOS 18",
    software_updates_years: 6,
    weight_g: 227,
    build_quality: "Titanium Frame, Ceramic Shield (2nd Gen) Front",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 7, NFC, Thread",
    overall_score: 96,
    performance_score: 99,
    camera_score: 97,
    battery_score: 89,
    gaming_score: 99,
    display_score: 98,
    value_for_money_score: 68,
    pros: JSON.stringify([
      "Exceptional gaming and processing speeds with A18 Pro",
      "Professional-grade 4K 120FPS Dolby Vision video capture",
      "New Camera Control touch capacitive key",
      "Excellent battery optimization"
    ]),
    cons: JSON.stringify([
      "Relatively slow charging speed capped at 30W",
      "Extremely expensive option",
      "Dynamic Island still blocks some display estate"
    ]),
    image_url: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 3,
    model: "OnePlus 13",
    launch_date: "2025-01-30",
    price_inr: 69999,
    display_size: 6.82,
    display_type: "BOE X2 LTPO OLED",
    refresh_rate: 120,
    resolution: "3168 x 1440 (QHD+)",
    processor: "Snapdragon 8 Elite",
    gpu: "Adreno 830",
    ram_gb: 12,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (Sony LYT-808, OIS) + 50MP Periscope (3x Zoom) + 50MP Ultra-wide",
    front_camera_spec: "32MP",
    battery_capacity: 6000,
    charging_speed: 100,
    wireless_charging: true,
    android_version: "Android 15 (OxygenOS 15)",
    software_updates_years: 4,
    weight_g: 213,
    build_quality: "Glass back, Aluminum frame",
    ip_rating: "IP69",
    network_support: "5G, Wi-Fi 7, NFC",
    overall_score: 95,
    performance_score: 98,
    camera_score: 93,
    battery_score: 99,
    gaming_score: 98,
    display_score: 97,
    value_for_money_score: 94,
    pros: JSON.stringify([
      "Incredible pricing for Snapdragon 8 Elite flagship",
      "Massive 6000mAh battery with 100W wired/50W wireless speeds",
      "IP68/IP69 rating for advanced water resistance",
      "Beautiful quad-curved BOE display"
    ]),
    cons: JSON.stringify([
      "Hasselblad processing can feel overly dramatic in portraiture",
      "Lacks 5x optical telephoto lens",
      "Bulky and large footprint in hand"
    ]),
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 4,
    model: "Pixel 9 Pro XL",
    launch_date: "2024-08-22",
    price_inr: 124999,
    display_size: 6.8,
    display_type: "Super Actua LTPO OLED",
    refresh_rate: 120,
    resolution: "2992 x 1344",
    processor: "Google Tensor G4 (4nm)",
    gpu: "Mali-G715 MC10",
    ram_gb: 16,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (OIS) + 48MP Telephoto (5x Optical) + 48MP Ultra-wide",
    front_camera_spec: "42MP",
    battery_capacity: 5060,
    charging_speed: 37,
    wireless_charging: true,
    android_version: "Android 14 (Upgradable)",
    software_updates_years: 7,
    weight_g: 221,
    build_quality: "Polished aluminum frame, Matte glass back",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 7, NFC, Satellite SOS",
    overall_score: 93,
    performance_score: 87,
    camera_score: 99,
    battery_score: 87,
    gaming_score: 84,
    display_score: 98,
    value_for_money_score: 74,
    pros: JSON.stringify([
      "Best-in-class AI capabilities and photo edits (Magic Editor)",
      "Completely bloatware-free clean Google software",
      "Stunning 42MP selfie camera with autofocus",
      "Full 7 years of prompt OS updates"
    ]),
    cons: JSON.stringify([
      "Tensor G4 runs warmer and is slower in heavy gaming",
      "Charging capped at a low 37W",
      "Higher pricing point in India"
    ]),
    image_url: "https://images.unsplash.com/photo-1598327106026-d9521da673d1?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 5,
    model: "Nothing Phone (2a) Plus",
    launch_date: "2024-07-31",
    price_inr: 27999,
    display_size: 6.7,
    display_type: "Flexible AMOLED",
    refresh_rate: 120,
    resolution: "2412 x 1084",
    processor: "MediaTek Dimensity 7350 Pro",
    gpu: "Mali-G610 MC4",
    ram_gb: 8,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (OIS) + 50MP Ultra-wide",
    front_camera_spec: "50MP",
    battery_capacity: 5000,
    charging_speed: 50,
    wireless_charging: false,
    android_version: "Android 14 (Nothing OS 2.6)",
    software_updates_years: 3,
    weight_g: 190,
    build_quality: "Polycarbonate back with Glyph interface",
    ip_rating: "IP54",
    network_support: "5G, Wi-Fi 6, NFC",
    overall_score: 87,
    performance_score: 82,
    camera_score: 84,
    battery_score: 91,
    gaming_score: 80,
    display_score: 89,
    value_for_money_score: 93,
    pros: JSON.stringify([
      "Beautiful, premium glyph-back LED design",
      "Upgraded 50MP selfie shooter captures crisp details",
      "Fast, bloat-free Nothing OS user experience",
      "Dimensity 7350 Pro gives solid midrange multitasking"
    ]),
    cons: JSON.stringify([
      "Plastic frame and back scratch easily",
      "No charger included in the packaging",
      "Low light zoom capabilities are limited"
    ]),
    image_url: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 6,
    model: "Redmi Note 14 Pro+",
    launch_date: "2024-09-26",
    price_inr: 32999,
    display_size: 6.67,
    display_type: "Curved CrystalRes OLED",
    refresh_rate: 120,
    resolution: "2712 x 1220 (1.5K)",
    processor: "Snapdragon 7s Gen 3",
    gpu: "Adreno 710",
    ram_gb: 12,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (Light Fusion 800, OIS) + 50MP Portrait (2.5x Zoom) + 8MP Ultra-wide",
    front_camera_spec: "20MP",
    battery_capacity: 6200,
    charging_speed: 90,
    wireless_charging: false,
    android_version: "Android 14 (HyperOS)",
    software_updates_years: 3,
    weight_g: 210,
    build_quality: "Gorilla Glass Victus 2 front, Glass back",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 6, NFC",
    overall_score: 89,
    performance_score: 82,
    camera_score: 89,
    battery_score: 98,
    gaming_score: 80,
    display_score: 92,
    value_for_money_score: 90,
    pros: JSON.stringify([
      "Exceptional 6200mAh Silicon-Carbon battery capacity",
      "Dedicated 50MP 2.5x optical zoom portrait lens",
      "Robust IP68 waterproof rating",
      "Gorgeous curved 1.5K OLED display"
    ]),
    cons: JSON.stringify([
      "HyperOS features preinstalled bloatware",
      "Slightly heavier weight profile (210g)",
      "Processor speed is average for intensive gaming"
    ]),
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 6,
    model: "Poco F6",
    launch_date: "2024-05-23",
    price_inr: 29999,
    display_size: 6.67,
    display_type: "Flow AMOLED",
    refresh_rate: 120,
    resolution: "2712 x 1220 (1.5K)",
    processor: "Snapdragon 8s Gen 3 (4nm)",
    gpu: "Adreno 735",
    ram_gb: 8,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (Sony LYT-600, OIS) + 8MP Ultra-wide",
    front_camera_spec: "20MP",
    battery_capacity: 5000,
    charging_speed: 90,
    wireless_charging: false,
    android_version: "Android 14 (HyperOS)",
    software_updates_years: 3,
    weight_g: 179,
    build_quality: "Polycarbonate frame and back",
    ip_rating: "IP64",
    network_support: "5G, Wi-Fi 6E, NFC",
    overall_score: 89,
    performance_score: 94,
    camera_score: 81,
    battery_score: 91,
    gaming_score: 95,
    display_score: 91,
    value_for_money_score: 96,
    pros: JSON.stringify([
      "Unbelievable gaming performance with Snapdragon 8s Gen 3 under 30k",
      "Very lightweight and comfortable plastic chassis (179g)",
      "90W fast charging with charger included in box",
      "High quality 1.5K display with 2400 nits peak brightness"
    ]),
    cons: JSON.stringify([
      "Plastic build does not feel very premium in hand",
      "Average ultra-wide camera performance",
      "HyperOS contains some system notifications/bloatware"
    ]),
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 2,
    model: "Galaxy A55",
    launch_date: "2024-03-15",
    price_inr: 39999,
    display_size: 6.6,
    display_type: "Super AMOLED",
    refresh_rate: 120,
    resolution: "2340 x 1080 (FHD+)",
    processor: "Exynos 1480 (4nm)",
    gpu: "Xclipse 530 (AMD RDNA 2)",
    ram_gb: 8,
    storage_gb: 128,
    expandable_storage: true,
    rear_camera_spec: "50MP Main (OIS) + 12MP Ultra-wide + 5MP Macro",
    front_camera_spec: "32MP",
    battery_capacity: 5000,
    charging_speed: 25,
    wireless_charging: false,
    android_version: "Android 14 (One UI 6.1)",
    software_updates_years: 4,
    weight_g: 213,
    build_quality: "Aluminum Frame, Gorilla Glass Victus+ Back",
    ip_rating: "IP67",
    network_support: "5G, Wi-Fi 6, NFC",
    overall_score: 84,
    performance_score: 75,
    camera_score: 83,
    battery_score: 88,
    gaming_score: 72,
    display_score: 88,
    value_for_money_score: 79,
    pros: JSON.stringify([
      "Premium glass-metal hybrid build that feels like the flagship S series",
      "Expandable microSD card slot supported",
      "Four major Android updates guaranteed",
      "Solid IP67 water and dust rating"
    ]),
    cons: JSON.stringify([
      "Thick display bezels look somewhat dated",
      "Slow 25W charging with no charger in the box",
      "GPU gaming support is limited for some graphic intensive games"
    ]),
    image_url: "https://images.unsplash.com/photo-1565630916779-e303be97b6f5?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 3,
    model: "Nord CE4",
    launch_date: "2024-04-01",
    price_inr: 24999,
    display_size: 6.7,
    display_type: "Fluid LTPS AMOLED",
    refresh_rate: 120,
    resolution: "2412 x 1080",
    processor: "Snapdragon 7 Gen 3",
    gpu: "Adreno 720",
    ram_gb: 8,
    storage_gb: 128,
    expandable_storage: true,
    rear_camera_spec: "50MP Main (Sony LYT-600, OIS) + 8MP Ultra-wide",
    front_camera_spec: "16MP",
    battery_capacity: 5500,
    charging_speed: 100,
    wireless_charging: false,
    android_version: "Android 14 (OxygenOS)",
    software_updates_years: 2,
    weight_g: 186,
    build_quality: "Plastic Frame and Back",
    ip_rating: "IP54",
    network_support: "5G, Wi-Fi 6, NFC",
    overall_score: 86,
    performance_score: 81,
    camera_score: 79,
    battery_score: 97,
    gaming_score: 80,
    display_score: 87,
    value_for_money_score: 93,
    pros: JSON.stringify([
      "Exceptional battery backup with huge 5500mAh capacity",
      "Crazy fast 100W SuperVOOC charger in the box",
      "Smooth OxygenOS experience with minimal bloatware",
      "Expandable memory slot (hybrid SIM slot)"
    ]),
    cons: JSON.stringify([
      "Plastic building materials feel cheap",
      "Only 2 years of Android platform upgrades",
      "Average portrait camera photo quality"
    ]),
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 8,
    model: "V40 Pro",
    launch_date: "2024-08-07",
    price_inr: 49999,
    display_size: 6.78,
    display_type: "Curved AMOLED",
    refresh_rate: 120,
    resolution: "2800 x 1260",
    processor: "MediaTek Dimensity 9200+",
    gpu: "Mali-G715 Immortalis",
    ram_gb: 12,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (Zeiss, OIS) + 50MP Telephoto (2x Optical) + 50MP Ultra-wide",
    front_camera_spec: "50MP",
    battery_capacity: 5500,
    charging_speed: 80,
    wireless_charging: false,
    android_version: "Android 14 (Funtouch OS 14)",
    software_updates_years: 3,
    weight_g: 192,
    build_quality: "Glass Back, Plastic Frame",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 7, NFC",
    overall_score: 91,
    performance_score: 92,
    camera_score: 94,
    battery_score: 94,
    gaming_score: 91,
    display_score: 92,
    value_for_money_score: 86,
    pros: JSON.stringify([
      "Zeiss co-engineered triple 50MP camera setup is class leading",
      "Zeiss portrait modes capture stunning DSLR-like bokeh",
      "Massive 5500mAh battery inside an ultra-slim 7.58mm body",
      "IP68 water resistance rating"
    ]),
    cons: JSON.stringify([
      "Funtouch OS has considerable preinstalled bloatware",
      "Plastic frame feels less premium for a 50k phone",
      "Single speaker layout is disappointing at this price tag"
    ]),
    image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 9,
    model: "Edge 50 Pro",
    launch_date: "2024-04-03",
    price_inr: 31999,
    display_size: 6.7,
    display_type: "Curved pOLED",
    refresh_rate: 144,
    resolution: "2712 x 1220 (1.2K)",
    processor: "Snapdragon 7 Gen 3",
    gpu: "Adreno 720",
    ram_gb: 8,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (OIS) + 10MP Telephoto (3x Optical) + 13MP Ultra-wide",
    front_camera_spec: "50MP",
    battery_capacity: 4500,
    charging_speed: 125,
    wireless_charging: true,
    android_version: "Android 14 (Hello UI)",
    software_updates_years: 3,
    weight_g: 186,
    build_quality: "Vegan Leather Back, Aluminum Frame",
    ip_rating: "IP68",
    network_support: "5G, Wi-Fi 6E, NFC",
    overall_score: 89,
    performance_score: 81,
    camera_score: 87,
    battery_score: 82,
    gaming_score: 79,
    display_score: 93,
    value_for_money_score: 91,
    pros: JSON.stringify([
      "Gorgeous vegan leather back design and curved 144Hz screen",
      "Unbelievable charging options: 125W wired AND 50W wireless support",
      "True clean Hello UI software with Moto gestures",
      "Full IP68 premium waterproof rating"
    ]),
    cons: JSON.stringify([
      "Slightly smaller 4500mAh battery capacity",
      "Camera shutter lag can cause missed fast action shots",
      "Updates schedule from Motorola is historically slow"
    ]),
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=60"
  },
  {
    brand_id: 7,
    model: "Reno 12 Pro",
    launch_date: "2024-06-18",
    price_inr: 36999,
    display_size: 6.7,
    display_type: "Curved AMOLED",
    refresh_rate: 120,
    resolution: "2412 x 1080",
    processor: "MediaTek Dimensity 7300-Energy",
    gpu: "Mali-G615 MC2",
    ram_gb: 12,
    storage_gb: 256,
    expandable_storage: false,
    rear_camera_spec: "50MP Main (Sony LYT-600, OIS) + 50MP Telephoto (2x Optical) + 8MP Ultra-wide",
    front_camera_spec: "50MP",
    battery_capacity: 5000,
    charging_speed: 80,
    wireless_charging: false,
    android_version: "Android 14 (ColorOS 14)",
    software_updates_years: 3,
    weight_g: 180,
    build_quality: "Glass Back, Plastic Frame",
    ip_rating: "IP65",
    network_support: "5G, Wi-Fi 6, NFC",
    overall_score: 86,
    performance_score: 80,
    camera_score: 87,
    battery_score: 90,
    gaming_score: 78,
    display_score: 89,
    value_for_money_score: 84,
    pros: JSON.stringify([
      "AI LinkBoost and AI Eraser 2.0 software features",
      "Excellent 50MP dedicated 2x portrait lens",
      "Hyper-fast 80W wired charging speed",
      "Lightweight, ultra-slim 7.4mm profile"
    ]),
    cons: JSON.stringify([
      "Plastic frame feels less durable for the price tag",
      "ColorOS has excessive push ads and recommended app folders",
      "Dimensity 7300-Energy processor performance is modest"
    ]),
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop&q=60"
  }
];

module.exports = {
  seedBrands,
  seedPhones
};
